version: '3.4'

services:
  app:
    build: 
      dockerfile: Dockerfile
      context: .
      args:
        - NODE_ENV=development
        - SERVICE_MAP=[{"name":"user-service","url":"http://host.docker.internal:3002/graphql"}]
    environment:
      - NODE_ENV=development
      - SERVICE_MAP=[{"name":"user-service","url":"http://host.docker.internal:3002/graphql"}]

    ports:
      - "5001:5001"
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
