version: '3.4'

services:
  user-api:
    build: 
      dockerfile: Dockerfile
      context: .
      args:
        - NODE_ENV=production
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
